# Generated by Django 5.2.5 on 2025-08-14 17:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("title", 1), ("cards", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text to display", "required": True},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Bold title text for this card, max length 100 chars",
                            "max_length": 100,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional text for this card, max length 255 chars",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image will be cropped to 400px by 370px"},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 2), ("text", 3), ("image", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.ListBlock", (5,), {}),
                    7: ("wagtail.blocks.StructBlock", [[("cards", 6)]], {}),
                },
                null=True,
            ),
        ),
    ]
