# Generated by Django 5.2.5 on 2025-08-16 00:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="miscpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("title", 1),
                    ("cards", 11),
                    ("image_and_text", 17),
                    ("cta", 19),
                    ("testimonial", 20),
                    ("pricing_table", 21),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text to display", "required": True},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Bold title text for this card, max length 100 chars",
                            "max_length": 100,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional text for this card, max length 255 chars",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image will be cropped to 400px by 370px"},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "More details", "max_length": 50},
                    ),
                    6: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    7: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_text", 5),
                                ("internal_page", 6),
                                ("external_link", 7),
                            ]
                        ],
                        {"help_text": "Enter a link or select a page"},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 2), ("text", 3), ("image", 4), ("link", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: ("wagtail.blocks.StructBlock", [[("cards", 10)]], {}),
                    12: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image will be cropped to 786px by 552px"},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Image to the left"),
                                ("right", "Image to the right"),
                            ],
                            "help_text": "Image on left with text on right or viceversa",
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Bold title text for this card, max length 60 chars",
                            "max_length": 60,
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Bold title text for this card, max length 140 chars",
                            "max_length": 140,
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_text", 5),
                                ("internal_page", 6),
                                ("external_link", 7),
                            ]
                        ],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 12),
                                ("image_alignment", 13),
                                ("title", 14),
                                ("text", 15),
                                ("link", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Max length 200 chars.", "max_length": 200},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 18), ("link", 16)]],
                        {},
                    ),
                    20: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (),
                        {
                            "target_model": "testimonials.Testimonial",
                            "template": "streams/testimonial_block.html",
                        },
                    ),
                    21: (
                        "streams.blocks.PricingTableBlock",
                        (),
                        {
                            "table_options": {
                                "autoColumnSize": False,
                                "colHeaders": False,
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                ],
                                "editor": "text",
                                "height": 108,
                                "minSpareRows": 0,
                                "renderer": "text",
                                "rowHeaders": True,
                                "startCols": 3,
                                "startRows": 3,
                                "stretchH": "all",
                            }
                        },
                    ),
                },
                null=True,
            ),
        ),
    ]
