# Generated by Django 5.2.5 on 2025-08-20 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, help_text="Enter your Facebook URL"),
                ),
                ("x", models.URLField(blank=True, help_text="Enter your X URL")),
                (
                    "youtube",
                    models.URLField(blank=True, help_text="Enter your Youtube URL"),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, help_text="Enter your Instagram URL"),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
